# org: aljeshishe3
# app: sls-ssh-docker
service: sls-ssh-docker

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  timeout: 400
  ecr:
    images:
      appimage:
        path: ./
#  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - '*'
#      Resource: 'arn:*:*:*:*:*'
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:*"
#          Resource: "*"

functions:
  handler:
    image: appimage
